- name: Create Secrets from Env Vars
  hosts: localhost
  gather_facts: yes
  vars:
    ns: slack-fastapi
  tasks:

    - name: Create namespace
      command: kubectl create namespace {{ ns }}
      ignore_errors: yes  

    - name: Create Registry secret
      command: >
        kubectl create secret docker-registry registrykey \
          --docker-server=redevops.gitlab.yandexcloud.net:5050 \
          --docker-username=container_registry \
          --docker-password={{ lookup('env', 'GITLAB_ACCESS_TOKEN') }} \
          -n {{ ns }}

    - name: Create Fastapi DB creds secrets
      command: >
        kubectl create secret generic fastapi-credentials \
          --from-literal=slack_fastapi_db_user={{ lookup('env', 'SLACK_FASTAPI_DB_USER') }} \
          --from-literal=slack_fastapi_db_pass={{ lookup('env', 'SLACK_FASTAPI_DB_PASS') }} \
          -n {{ ns }}

    - name: Create Postgres creds secrets
      command: >
        kubectl create secret generic postgres-credentials \
          --from-literal=postgres_user={{ lookup('env', 'POSTGRES_USER') }} \
          --from-literal=postgres_password={{ lookup('env', 'POSTGRES_PASSWORD') }} \
          -n {{ ns }}

    - name: Create Rabbitmq creds secrets
      command: >
        kubectl create secret generic rabbitmq-credentials \
          --from-literal=rabbitmq_user={{ lookup('env', 'RABBITMQ_USER') }} \
          --from-literal=rabbitmq_password={{ lookup('env', 'RABBITMQ_PASSWORD') }} \
          -n {{ ns }}
