- name: Apply Helm
  hosts: localhost
  gather_facts: yes
  vars:
    ns: traefik
    ingress_name: traefik-ingress
    kubeconfig_path: /home/groot/.kube/config
    traefik_version: v25.0.0 # docker version 2.10
    cert_manager_namespace: cert-manager
    cert_manager_version: v1.8.0
    email_address: mats.tumblebuns@gmail.com
    folder_id: b1gjev1g87fgira75vkt

  tasks:
    - name: Create traefik namespace
      command: kubectl create namespace {{ ns }}
      ignore_errors: yes  

    - name: Create cert-manager namespace
      command: kubectl create namespace {{ cert_manager_namespace }}
      ignore_errors: yes  

    - name: Add Traefik Helm Repository
      command: helm repo add traefik https://helm.traefik.io/traefik
      ignore_errors: yes

    - name: Update CRDs
      command: kubectl apply -f https://raw.githubusercontent.com/traefik/traefik/v2.10/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
      retries: 3
      delay: 10

    - name: Remove existing cert-manager-webhook-yandex directory
      file:
        path: "{{ playbook_dir }}/cert-manager-webhook-yandex"
        state: absent
      ignore_errors: yes

    - name: Add Gateway Rbac Role for Traefik
      command: kubectl apply -f traefik-rbac-role.yml
      retries: 3
      delay: 10

    - name: Install Traefik Helm Chart
      command: helm upgrade --install {{ ingress_name }} traefik/traefik \
        --namespace {{ ns }} \
        --kubeconfig {{ kubeconfig_path }} \
        --values=traefik-values-yc.yml \
        --version {{ traefik_version }}
      retries: 3
      delay: 10

    - name: Install cert-manager CRDs
      command: kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.8.0/cert-manager.crds.yaml
      ignore_errors: yes

    - name: Add cert-manager Helm Repository
      command: helm repo add jetstack https://charts.jetstack.io
      ignore_errors: yes

    - name: Update Helm Repositories
      command: helm repo update
      ignore_errors: yes

    - name: Install cert-manager and Yandex Cloud DNS plugin
      shell: |
        export HELM_EXPERIMENTAL_OCI=1 && \
        helm pull oci://cr.yandex/yc-marketplace/yandex-cloud/cert-manager-webhook-yandex/helm/cert-manager-webhook-yandex \
          --version 1.0.6 \
          --untar && \
        helm install \
          --namespace {{ cert_manager_namespace }} \
          --create-namespace \
          cert-manager-webhook-yandex ./cert-manager-webhook-yandex/
      ignore_errors: yes

    - name: Create Cert-manager SA key
      command: kubectl create secret generic k8s-sa-key --from-file=k8s-sa-key.pem=/home/groot/.ssh/k8s-sa-key.pem -n cert-manager
    
    - name: Apply ClusterIssuer configuration
      command: kubectl apply -f traefik-certs-yc.yml
