- name: Deploy GitLab Runner
  hosts: localhost
  gather_facts: yes
  vars:
    ns: gitlab
    # for DO
    # gitlab_url: "https://solarwinds123.ru"
    # for YC
    gitlab_url: "https://redevops.gitlab.yandexcloud.net"
    values_file: "gitlab-runner-values.yml"

  tasks:

    - name: Ensure the namespace exists
      command: kubectl create namespace {{ ns }}
      ignore_errors: yes  

    - name: Ensure the namespace exists
      command: kubectl create namespace slack-fastapi
      ignore_errors: yes  

    - name: Add permissions to Gitlab Runner
      command: kubectl apply -f gitlab-runner-rbac.yml

    - name: Create Kubernetes secret for GitLab Runner Token
      shell: |
        kubectl create secret generic gitlab-runner-token \
        --from-literal=runner-token={{ lookup('env', 'GITLAB_RUNNER_TOKEN') }} \
        --namespace {{ ns }}
      ignore_errors: yes

    - name: Install GitLab Runner
      shell: |
        TOKEN=$(kubectl get secret gitlab-runner-token --namespace {{ ns }} -o jsonpath="{.data.runner-token}" | base64 --decode)
        helm upgrade --install gitlab-runner gitlab/gitlab-runner \
        --namespace {{ ns }} \
        --set-string runnerRegistrationToken=$TOKEN \
        -f {{ values_file }}
