apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: yc-clusterissuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mats.tumblebuns@gmail.com
    privateKeySecretRef:
      name: letsencrypt-private-key
    solvers:
    - dns01:
        webhook:
          groupName: acme.cloud.yandex.com
          solverName: yandex-cloud-dns
          config:
            folder: b1gjev1g87fgira75vkt
            serviceAccountSecretRef:
              name: k8s-sa-key
              key: k8s-sa-key.pem
