apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gateway-role
rules:
  - apiGroups: [""]
    resources:
      - services
      - endpoints
      - secrets
      - namespaces
    verbs:
      - get
      - create
      - list
      - watch
      - update
      - patch
  - apiGroups: ["apps"]
    resources: [ "deployments" ]
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources:
      - ingresses
      - ingressclasses
      - ingresses/status
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups: ["traefik.containo.us"]
    resources:
      - ingressroutes
      - ingressroutetcps
      - ingressrouteudps
      - middlewares
      - middlewaretcps
      - tlsoptions
      - tlsstores
      - traefikservices
      - serverstransports
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups: ["gateway.networking.k8s.io"]
    resources:
      - gatewayclasses
      - gateways
      - httproutes
      - tcproutes
      - tlsroutes
      - gatewayclasses/status
      - gateways/status
      - httproutes/status
      - tcproutes/status
      - tlsroutes/status
    verbs:
      - get
      - list
      - watch
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gateway-role-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gateway-role
subjects:
  - kind: ServiceAccount
    name: traefik-ingress
    namespace: traefik  # Updated to the correct namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gateway-role-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gateway-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: traefik  # Updated to the correct namespace
